### PR TITLE
Allow net-ssh v7

### LINKED ISSUE #136: Allow use of `net-ssh` v7.0.0 (for OpenSSL 3 compatibility)
This gem has a dependency on `net-ssh` with a range of `">= 5.0.0", "< 7.0.0"`.

However `net-ssh` v7 was just released, with fixes for OpenSSL 3:
https://rubygems.org/gems/net-ssh/versions/7.0.0
https://github.com/net-ssh/net-ssh/pull/864

Please can this gem be updated to support v7 of `net-ssh`, so it can be used with OpenSSL 3?

Many thanks!

https://github.com/net-ssh/net-sftp/blob/900775d32e9bf0706b9ca4fee2e01a83084d0a04/net-sftp.gemspec#L34

### PR DESCRIPTION
**Pull request by dzuelke**
... which fixes OpenSSL 3 compat.

Closes #136

### CODE REVIEW

**Comment by schinery** [comment]
@mfazekas is it possible to get this out in a release? 🙏🏻

**Comment by mfazekas** [comment]
@schinery I'll try to look into it. Pls get back to me if it doesn't happen in 2 weeks

**Comment by edmorley** [comment]
@mfazekas I don't suppose you'd have a spare moment to do a release in the next few days? :-)

**Comment by donv** [comment]
Getting this into a new release would be great!

**Pull request merged**
