### PR TITLE
Fix compatiblity with net-ssh 4.0+

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Comment by nabilbendafi** [comment]
@delano @mfazekas: As maintainers of this packet, could you provide an estimated date for integrating this #59 PR ?
Since it seems to block #60, #61 and #62.

**Comment by mfazekas** [comment]
@voxik thanks for the PR, sorry for the late response! 👍

**Comment by nabilbendafi** [comment]
Thanks.

**Comment by voxik** [comment]
My pleasure 👍 Thx for merge.

**Pull request merged**
